Fname=input("Enter the first student's name :" )
Fid=input("Enter the first student's ID :" )
Fgrade=float(input("Enter the first student's grade :" ))
Sname=input("\nEnter the second student's name :" )
Sid=input("Enter the second student's ID :" )
Sgrade=float(input("Enter the second student's grade :" ))
print('informat for students and their"math" grades\n'+ Fname +" (id"  ,Fid ,") got grade: " ,Fgrade,"\n" +Sname + "(id"  , Sid ,") got grade: " ,Sgrade)
print("Average math grade is ",(Fgrade +Sgrade)/2 )