first_num=float(input("Enter first number:"))
second_num=float(input("Enter second number:"))
print(first_num,"+",second_num,"=",first_num+second_num)
print(first_num,"-",second_num,"=",first_num-second_num)
print(first_num,"*",second_num,"=",first_num*second_num)
print(first_num,"/",second_num,"=",first_num/second_num)
